org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=1.21.1
loader_version=21.1.252
java_version=21
mod_version=1.0.1
mod_id=skylasliver_creeperphantom
mod_name=苦力怕幻翼
mod_license=MIT
maven_group=dev.skylasliver.creeperphantom
archives_base_name=skylasliver_creeperphantom
neo_version=21.1.252
